services:
  db:
    image: postgres:15
    container_name: f1stratos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jj00
      POSTGRES_DB: f1stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  f1-db:
    build:
      context: .
      args:
        - STALKER_USER=${STALKER_USER}
        - STALKER_PWD=${STALKER_PWD}
    container_name: f1_mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/db/mongo_data2:/data/db
volumes:
  postgres_data:
  mongo_data:
