name: f1-stratos-stack
services:
  mongodb:
    build:
      context: ./Backend/DB
      dockerfile: Dockerfile.mongo
    image: f1stratos-mongodb:1.0.0
    container_name: f1stratos_mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${F1_DB_NAME}
    volumes:
      - /home/db/mongo-data:/data/db
    networks:
      - f1stratos-network

  mongo-stalker:
    build:
      context: ./Backend/Mongo-Stalker
      dockerfile: Dockerfile.mongostalker
    image: mongo-stalker:1.0.0
    container_name: f1stratos_mongo-stalker
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - F1_APP_USER=${F1_APP_USER}
      - F1_APP_PASSWORD=${F1_APP_PASSWORD}
      - IP_DATABASE_MD=${IP_DATABASE_MD}
      - PORT_DATABASE_MD=${PORT_DATABASE_MD}
    depends_on:
      - mongodb
    networks:
      - f1stratos-network

networks:
  f1stratos-network:
    driver: bridge

