version: '3.8'

services:
  db:
    image: postgres:15
    container_name: f1stratos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jj00
      POSTGRES_DB: f1stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
